name: donutcolors
description: Package containing all standard Donut colors.
version: 1.1.0
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
